name: "Github Uploader for Salesforce Unified Knowledge"
description: "Executing zipping and sending the ZIP to AWS S3 bucket"

inputs:
  aws-key-id:
    description: "AWS key id"
  aws-secret-access-key:
    description: "AWS secret access key"
  aws-region:
    description: "AWS region"
  aws-bucket:
    description: "AWS bucket"
  aws-folder:
    description: "AWS folder"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Zipping files
      run: zip -r ${{ github.event.repository.name }}.zip . -x '*.git*' '*.idea*'
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Copy files to the test website with the AWS CLI
      shell: bash
      run: |
        aws s3 cp ${{ github.event.repository.name }}.zip s3://${{ inputs.aws-bucket }}/${{ inputs.aws-folder }}/${{ github.event.repository.name }}.zip
    

branding:
  icon: "archive"
  color: "gray-dark"
